stm32-rs/stm32f0xx-hal

- examples/blinky_delay.rs
- src/gpio.rs
Adds an implementation of the software toggleable trait from embedded-hal to the pins from the gpio module.
> Added implementation of the default toggleable trait

- .travis.yml
- Cargo.toml
- README.md
- src/gpio.rs
- src/i2c.rs
- src/lib.rs
- src/rcc.rs
- src/serial.rs
- src/spi.rs
Currently adds
- GPIO
- UART (partial)
- RCC
Currently it's hard to conditionally add some peripherals. I'd wrap then in a macro, especially for the uarts, since stm32f030xc has 6 of them.
The question is also how to do the multiple pin combinations for AF configurations. Individually adding them is a bit inconvenient. Is there any concrete reasoning behind having pin combinations and not just individual pins with usartRX/usartTX/i2cSDA/i2cSCL traits?
> [WIP] Add implementation for stm32f030

- examples/blinky_multiple.rs
- src/gpio.rs
Result of discussion on #2. Adds an implementation of fully erased pins that works based on trait implementation. Currently uses a macro definition to assign the trait, this may be fixed later by some work done to svd2rust to make gpio register block definition more standard.
Based on and features code by @david-sawatzke from his PR #2.
> Fully erased pins based on trait implementations

- .travis.yml
- Cargo.toml
- examples/blinky_timer.rs
- memory.x
- src/lib.rs
- src/timers.rs
Almost completely based on https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/timer.rs.
> Add timer implementation

- Cargo.toml
- src/gpio.rs
- src/i2c.rs
- src/serial.rs
- src/spi.rs
- src/timers.rs
- Serial is now structured like in https://github.com/stm32-rs/stm32f4xx-hal/pull/48/, so there is no giant macro repeating code
- I2C1 & I2C2 is there
- SPI1 & SPI2 is there
- (Maybe) Port examples so they work on all variants (Opened a separate issue for that)
> Add more peripherals for the stm32f030

- CHANGELOG.md
- src/delay.rs
- src/timers.rs
Just delays multiple times
Builds not in release mode often don't fit on target hardware and so it's easy to accidentally overflow.
For example, 500 ms with 48 MHz is too much
Also adds some documentation to the delay module and adds a warning to the systick implementation of timer.
> Allow larger systick delays

- Cargo.toml
- examples/led_hal_button_irq.rs
- examples/spi_hal_apa102c.rs
The spi example already works, but I've only improved `led_hal_button_irq` a bit. There's a bit of inconsistent naming, heres accompanying issue https://github.com/stm32-rs/stm32-rs/issues/122. Not sure if it will ever completely be the same.
> Make examples more generic

- CHANGELOG.md
- src/delay.rs
A lot of device crates need a delay instances, see https://github.com/JohnDoneth/hd44780-driver and https://github.com/yuri91/ili9341-rs. Having to pass a delay instance as needed isn't very ergonomic. I think multiple delay instances are often needed. There are multiple ways to do this (that I can think of):
- Allow a delay instance based on asm delay loops (probably needs ramfunc because of wait states)
- Allow normal timers to be used for delays
- Allow multiple instances using the systick timer read only 
I used the last way, leaving the systick always running, getting the timer value at the beginning and comparing it to the current one (including some amount of leeway so that long interrupts can't easily overflow). The first commit also fixes #21 (just a typo). We technically don't …
> Allow multi delay instances for the systick timer

- examples/serial_spi_bridge.rs
I've chosen to use the nb api, but I'm open to changing it to the `Transfer`-trait if so desired
Tested on hardware, works
> Add a basic spi example which isn't dependent on external components

- .travis.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- src/adc.rs
- src/gpio.rs
- src/i2c.rs
- src/lib.rs
- src/rcc.rs
- src/serial.rs
- src/spi.rs
- src/timers.rs
Adds device support for the [STM32F091](https://www.st.com/en/microcontrollers/stm32f0x1.html?querycriteria=productId=LN7). Let me know if anything needs fixing.
> Add support for the STM32f091

- CHANGELOG.md
- src/rcc.rs
This adds a `clock_src` param to the `CFGR` builder and the accompanying code to enable the `HSE` clock in `freeze`. This supports using the HSE both by itself and as input to the PLL and can be used by simply adding a `.hse` call like so:
```rust
let clocks = rcc.cfgr.hse(16.mhz()).sysclk(32.mhz()).freeze();
```
> RCC: Add ability to use HSE clock source

- README.md
As the title suggest, I went through and tidied up the README, added missing links, etc. As requested in #10 I also added a basic Getting Started section.
I understand this stuff is all pretty subjective, so if there are any changes that aren't sitting well with anybody just let me know and I have no problem making some modification.
> Overhaul README, add Getting Started section

- CHANGELOG.md
- src/delay.rs
I tried to optimize the delay implementation a bit. It gets now inlined (without division) in blinky_delay and makes led_hal_button_irq a bit smaller. Unfortunately the division is still in the delay method (here for blinky_multiple):
```
0800027c <_ZN97_$LT$stm32f0xx_hal..delay..Delay$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17hee9179c2bd627785E>:
800027c:	b570      	push	{r4, r5, r6, lr}
800027e:	2801      	cmp	r0, #1
8000280:	d105      	bne.n	800028e <_ZN97_$LT$stm32f0xx_hal..delay..Delay$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8delay_ms17hee9179c2bd627785E+0x12>
8000282:	2900      	cmp	r1, #0
8000284:	d018      	beq.n	80002b8 <_ZN97_$LT$stm32f0xx_hal..delay..Delay$u20$as$u20$embedded_hal..blocking..delay..DelayMs$LT$u16$GT$$GT$8de …
```
> Optimize delay implementation

- CHANGELOG.md
- examples/serial_echo.rs
- examples/watchdog.rs
- src/serial.rs
This also makes the serial stuff in https://github.com/stm32-rs/stm32f0xx-hal/pull/27 obsolete. 
Additionally by virtue of how it works also implements https://github.com/stm32-rs/stm32f4xx-hal/pull/49 here.
Not sure how we should handle the release method. It currently works but you get a `()` for the unused pin back.
Currently untested
> Add a tx only and a rx only serial instance

- CHANGELOG.md
- Cargo.toml
- examples/usb_serial.rs
- src/lib.rs
- src/usb.rs
See also: https://github.com/stm32-rs/stm32-usbd/pull/16
> Add USB driver

- examples/adc_values.rs
- examples/flash_systick.rs
- examples/flash_systick_fancier.rs
systick() should return `()`. This fixes build errors that CI has been reporting.
> systick returns, so should be marked as such.

- CHANGELOG.md
- src/rcc.rs
The PLL was not locking on a F070RB. Part of the reason was that the CR register was written instead of modified. This, plus fixed computation of the PLL multiplier (similar to #78) and #80, allows the PLL to lock.
(If I should first create an issue for this, or should combine all small changes together into one PR, let me know).
> RCC: PLL: Modify CR instead of write, plus remove unnecessary unsafe

- CHANGELOG.md
- src/rcc.rs
This adds an RCC API feature to set the USB clock source. This is necessary for STM32F070 and also if a crystal is desired to be used for a USB clock (instead of the RCC).
Similar to yesterday's patch, this has lots of `cfg` attributes to control which features are available for the various MCU models. It looks like we could create a new attribute macro like `cfg_has_usb` to apply the proper device list, but I'm leaning towards the simplicity of what this PRcontains.
This does not yet make USB F070 USB work (yet), as the PLL multipliers are not calculated correctly (related to #78), but it is another step in that direction. 
This should close #83.
> RCC: USB source switching code.

- CHANGELOG.md
- src/rcc.rs
- tools/check.py
This adds logic to determine if HSI/2 is an available clock source (instead of HSI/PLLDIV), and fixes a few logic errors:
* Disable CI build if stm32f030 is specified without the more specific stm32f030
* Add RCC_PLLSRC_PREDIV1_SUPPORT constant to specify if the PLLSRC register is one or two bits. Note that this is erring on the side of the reference manual. The CMSIS headers and ST HAL show that the F070 should support PREDIV1 (and hardware does work). A source code comment has been added about this. It's possible that F030xC also has support. The stm32f0 crate would need to be modified to enable two-bit PLLSRC for these models.
* Correct PLL multiplier computation to depend on what the predivisor is set to.
* If the multiplier was 2, PLL was not being enabled. This lets it be enabled.
* …
> RCC: Correct PLL multiplier calculations.

- CHANGELOG.md
- src/timers.rs
Internally the frequency going to the timers is doubled if PCLK is
prescaled.
Fixes #90
> Assume twice the timer frequency when HCLK != PCLK

- src/serial.rs
> Use core::convert::Infallible instead of void::Void for USARTs

- CHANGELOG.md
- src/serial.rs
Clearing the error bits once should suffice
> Simplify serial `read()` error handling

- Cargo.toml
None of the library code seems to depend on `cortex-m-rt`, only the examples do.
> Make cortex-m-rt a dev-dependency only

- examples/usb_serial.rs
- src/usb.rs
I'd also prefer it taking the hal `Rcc`, but that'd be a breaking change. @therealprof Your thoughts?
> Update `remap_pins` stuff

- src/spi.rs
Closes #130
---
Continuing discussion from #130 :
The suggested implementation was replacing this:
```rust
self.check_send().ok(); 
Ok(()) 
```
With this:
```rust
nb::block!(self.check_send())
```
The concern I have with that is it seems the last `check_send().ok()` was intended to clear the `OVR` error bit that may be set due to dropped reads.
Additionally, it does not seem that this works as intended, the CS still goes high before the write is completed with consecutive write calls.
> Poll for completion on SPI write.

- CHANGELOG.md
- Cargo.toml
- src/can.rs
This changes the CAN API to use the [bxcan](https://github.com/jonas-schievink/bxcan) crate, a reusable driver for the bxCAN peripherals in many low- to middle-end STM32 MCUs.
> bxcan-based CAN interface

- CHANGELOG.md
- examples/pwm.rs
- src/lib.rs
- src/pwm.rs
- src/timers.rs
Add PWM support based on the stm32f4xx_hal implementation. It is mostly a copy from stm32f4xx_hal with some modification.
Only change to stm32f4xx_hal: it uses the recommended order for setting the register from DM00042534
I did some testing based on a stm32f030c8 chip.
fixes #26
> PWM support

- CHANGELOG.md
- Cargo.toml
- src/pwm.rs
- tools/check.py
The clippy failures look like a pre-existing condition.  I can clean those up in a separate PR if desired.
> Update stm32f0 peripheral access crate from 0.13 to 0.14

- CHANGELOG.md
- src/rcc.rs
- src/time.rs
- src/watchdog.rs
This resolves these 6 clippy failures:
```text
warning: name `HSI` contains a capitalized acronym
--> src/rcc.rs:93:9
|
93 |         HSI,
|         ^^^ help: consider making the acronym lowercase, except the initial letter (notice the capitalization): `Hsi`
|
= note: `#[warn(clippy::upper_case_acronyms)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
warning: name `HSE` contains a capitalized acronym
--> src/rcc.rs:95:9
|
95 |         HSE(u32, super::HSEBypassMode),
|         ^^^ help: consider making the acronym lowercase, except the initial letter: `Hse`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
warning: an implementation of …
```
> fix new clippy lints

- CHANGELOG.md
- src/pwm.rs
When configuring a 2-channel PWM and setting up channel 2 mode, we accidentally set up channel 1 mode instead.
I haven't actually verified the currently broken behaviour on hardware since I'm using 4-channel PWM where this configuration is done correctly, but this one looks like a simple copy-paste error which I spotted while studying the code :sweat_smile:
> Set mode correctly on C2 of 2-channel PWM

- README.md
Building only for f030 doesn't work:
https://github.com/stm32-rs/stm32f0xx-hal/issues/148
https://github.com/stm32-rs/stm32f0xx-hal/issues/121
> Fix readme example build

- CHANGELOG.md
- src/serial.rs
Noticed that the serial interface were missing access to these flags and seem to be present in other stm32xx hals (like stm32f4xx-hal).
Added them so that an ISR can differ between these events.
Edit: removed unnecessary unsafe.
> Provide access to serial status flags idle/txe/rxne

- CHANGELOG.md
- src/timers.rs
Timer interrupts cannot be used without this method.
> Provide ability to clear timer UIF interrup flag

- CHANGELOG.md
- examples/pwm_complementary.rs
- src/pwm.rs
- src/timers.rs
Issue #162 created by *myself*.
TL;DR: PWM module did not support complementary channels, it should.
- Add CHxN pins, (traits?), and structs and whatnot
- Set `OSSR` and `CCxNE` registers accordingly
I have only confirmed it works on CH1/CH1N, but I don't see why it wouldn't work on the others.
This is my first time using Rust.
> Add Basic Complementary Channel Support to PWM

- CHANGELOG.md
- examples/adc_values.rs
- The `adc_values` example had a conversion error. `VTemp` is in 10th's of a degree, not hundredths
- Line `82` replace `100` with `10`
> Fix ADC Example Temperature Conversion

- CHANGELOG.md
- src/rcc.rs
- src/spi.rs
With rust version 1.73.0 the `invalid_reference_casting` lint was set to deny by default. (See [PR#112431](https://github.com/rust-lang/rust/pull/112431). This causes the build process of this crate to fail to build spi.rs (only when building the crate with its examples, when adding it as a dependency works fine from what i can see).
This change fixes the compilation by adding the `[allow(invalid_reference_casting)]` attribute to the relevant parts.
This also fixes a `unused doc comment` compilation warning in rcc.rs
I have not tested this on hardware, just added the attribute to fix the compilation.
> Fix compilation error in spi.rs for rust Version 1.73+

- CHANGELOG.md
- src/pwm.rs
- src/timers.rs
This adds the option to use the complementary PWM Channels of Timers with 1 Channel and a complementary output in standalone mode. (E.g. using CH1N (PB6) of TIM16 without using CH1)
This has been tested and is working on a STM32F072B-DISCO board.
*NOTE:* The CI will probably fail until #170 or an alternative is merged.
> Add PWM standalone output on complementary PWM Channels

- CHANGELOG.md
- Cargo.toml
- examples/flash_read_write.rs
- src/flash.rs
- src/lib.rs
- src/signature.rs
This implements an interface to reading and writing to the internal flash memory. This implements the [`NorFlash` traits](https://github.com/rust-embedded-community/embedded-storage/blob/master/src/nor_flash.rs) from the [`embedded-storage` crate](https://docs.rs/embedded-storage/latest/embedded_storage/).
The interface is inspired by the interfaces used in the [`stm32f4xx-hal`](https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/flash.rs) and the [`stm32g0xx-hal`](https://github.com/stm32-rs/stm32g0xx-hal/blob/main/src/flash/mod.rs). 
The interface could definitely use some clean up and I'm open to suggestions on that matter. Especially the handling of [writing to addresses not aligned to the native write size](https://github.com/JanekGraff/stm32f0xx-hal/blob/2769e82dfa8e42b74f7e367 …
> Implement interface to internal flash storage

- CHANGELOG.md
- Cargo.toml
This version implements the embedded-can traits.
See [#59 in bxcan](https://github.com/stm32-rs/bxcan/pull/59) for more info.
> Update bxcan dependency to 0.8.0
