- src/i2c.rs
- src/spi.rs
Pretty straight forward, should be self-explanatory.
> Add SPI and I2C support for STM32F070 devices

- examples/watchdog.rs
- src/lib.rs
- src/prelude.rs
- src/watchdog.rs
> Add a watchdog implementation

- CHANGELOG.md
- src/gpio.rs
With reasons why it's safe to do so
> Add Send & Sync impls for Pin

- CHANGELOG.md
- Cargo.toml
- examples/adc_values.rs
- src/adc.rs
Test implementation of the helper functions for various ADC internal sensors. Currently untested on actual hardware.
> Initial test implementation of ADC helper functions

- src/spi.rs
A basic example and an overview over the limitations
> Add more spi documentation

- Cargo.toml
> Add myself to authors list

- Cargo.toml
- src/gpio.rs
- src/i2c.rs
- src/serial.rs
- src/spi.rs
- src/timers.rs
Basically just went through every `stm32f0xx` datasheet and did my best to ensure the code base matches the datasheets. There may still be some discrepancies, but I did my best to double-check everything and I did manage to find a handful of errors and omissions.
Also added myself to the authors list in `Cargo.toml` as suggested by @therealprof , thanks again!
> Review peripherals and fix inconsistencies

- CHANGELOG.md
- src/adc.rs
> Use modify instead of write for HSI14 clock setup

- CHANGELOG.md
- src/lib.rs
- src/tsc.rs
> First completish version of the TSC support

- CHANGELOG.md
- Cargo.toml
> Release v0.13.0

- CHANGELOG.md
- src/rcc.rs
> Enable CRS support for USB

- examples/i2c_find_address.rs
I added an example to find all addresses of connected i2c devices.
It's a little arbitrary in which it does not show any outside effect; one is meant to run it step by step and inspect the final values with gdb.
> Added an example for i2c

- CHANGELOG.md
- src/serial.rs
> Clear error flags before returning

- src/gpio.rs
> Improve legibility by having a single macro structure for all pins

- CHANGELOG.md
- src/rcc.rs
Closes #79 
This is an API change to allow "bypass" mode to be used for the HSE.
> Add (breaking) API change to allow for HSE bypass to be selected.

- src/rcc.rs
This modifies the RCC module to provide the HSI48 and CRS API for devices which have it (based on the reference manual). The manual states that all devices with HSI48 have CRS. I don't envision it would often be used without USB, but there may be a use to someone.
I don't like how much replication of "cfg" statements this patch has. Let me know if there is a better way to code this (or if we should just leave the API in place for devices without the proper hardware).
EDIT: Another option would be to split the 0x1/0x2/0x8 "inner" module into one for devices with HSI48, and a second for devices without HSI48.
> RCC: Only provide HSI48 & CRS in API for devices which have it

- CHANGELOG.md
- Cargo.toml
- examples/blinky_timer_irq.rs
> Add a new timer and interrupt based blinky example

- .travis.yml
- README.md
> Mention MSRV of 1.39.0 and test it in CI

- src/rcc.rs
> Fix pllsrc bits for HSE

- src/serial.rs
This code seems to originate from the very first stm32f103xx-hal commit:
https://github.com/japaric/stm32f103xx-hal/commit/9cb1629b771e63fee85717b23f59b7c0dbd08014
I don't see why there should be any difference between 8-bit and 32-bit access to these registers.
> Replace volatile access with pac register read/write

- CHANGELOG.md
- Cargo.toml
> Bump stm32f0 to 0.10

- Cargo.toml
> Add thumbv6m-none-eabi target to docs.

- CHANGELOG.md
- examples/serial_spi_bridge.rs
- src/spi.rs
> Optimize 8-bit SPI transfers and add 16-bit SPI transfers

- CHANGELOG.md
- Cargo.toml
> Bump version to 0.17.0 and prepare release

- CHANGELOG.md
- src/tsc.rs
some touch pins were missing the TscPin trait
> implement TscPin for remaining touch pins

- CHANGELOG.md
- Cargo.toml
- src/usb.rs
> Bump all dependencies and add missing CHANGELOG entries

- .github/workflows/changelog.yml
> Add CHANGELOG update check to CI

- CHANGELOG.md
- src/adc.rs
- src/i2c.rs
- src/lib.rs
- src/serial.rs
- src/spi.rs
> Address a few clippy lints

- CHANGELOG.md
- src/adc.rs
It was not working and unnecessarily complicated
> Fix VTemp conversion

- CHANGELOG.md
- Cargo.toml
> Update bxcan from 0.4 to 0.6

- CHANGELOG.md
- Cargo.toml
- README.md
> Release 0.8.0

- CHANGELOG.md
- Cargo.toml
`cast` changelog: [CHANGELOG.md](https://github.com/japaric/cast.rs/blob/v0.3.0/CHANGELOG.md#v030---2021-09-04)
> Update cast from 0.2 to 0.3
